<?php
declare(strict_types=1);


$authors = [
    ['id'=>1,
    'name'=>'Michaela Lundborg',
    ],
    ['id'=>2,
    'name'=>'Jacob Fridmar',
    ],
    ['id'=>3,
    'name'=>'Alexander Gustafsson Flink',
    ],
    ['id'=>4,
    'name'=>'Betsy Alva Soplin',
    ],
    ['id'=>5,
    'name'=>'Victor Ljungblad',
    ]
];

$posts = [
    ['title'=>'Cat',
    'image'=>'img/cat.jpg',
    'content'=> 'Nori grape silver beet broccoli kombu beet greens fava bean potato quandong celery. Bunya nuts black-eyed pea prairie turnip leek lentil turnip greens parsnip. Sea lettuce lettuce water chestnut eggplant winter purslane fennel azuki bean earthnut pea sierra leone bologi leek soko chicory celtuce parsley jícama salsify' ,
    'author_id'=>1,
    'date'=>'2019-08-01',
    'likes'=> 30,
    ],
    ['title'=>'Gorilla',
    'image'=>'img/gorilla.jpg',
    'content'=> 'Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.',
    'author_id'=>1,
    'date'=>'2019-08-21',
    'likes'=> 1,
    ],
    ['title'=>'Lemur',
    'image'=>'img/lemur.jpg',
    'content'=> 'Celery quandong swiss chard chicory earthnut pea potato. Salsify taro catsear garlic gram celery bitterleaf wattle seed collard greens nori. Grape wattle seed kombu beetroot horseradish carrot squash brussels sprout chard.',
    'author_id'=>2,
    'date'=>'2019-08-20',
    'likes'=> 54,
    ],
    ['title'=>'Sheep',
    'image'=>'img/sheep.jpg',
    'content'=> 'Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula pea tatsoi aubergine spring onion bush tomato kale radicchio turnip chicory salsify pea sprouts fava bean. Dandelion zucchini burdock yarrow chickpea dandelion sorrel courgette turnip greens tigernut soybean radish artichoke wattle seed endive groundnut broccoli arugula.',
    'author_id'=>2,
    'date'=>'2019-08-08',
    'likes'=> 65,
    ],
    ['title'=>'Giraffe',
    'image'=>'img/giraffe.jpg',
    'content'=> 'Celery quandong swiss chard chicory earthnut pea potato. Salsify taro catsear garlic gram celery bitterleaf wattle seed collard greens nori. Grape wattle seed kombu beetroot horseradish carrot squash brussels sprout chard.',
    'author_id'=>3,
    'date'=>'2019-08-03',
    'likes'=> 7,
    ],
    ['title'=>'Seal',
    'image'=>'img/seal.jpg',
    'content'=> 'Turnip greens yarrow ricebean rutabaga endive cauliflower sea lettuce kohlrabi amaranth water spinach avocado daikon napa cabbage asparagus winter purslane kale. Celery potato scallion desert raisin horseradish spinach carrot soko.',
    'author_id'=>3,
    'date'=>'2019-08-04',
    'likes'=> 76,
    ],
    ['title'=>'Cats',
    'image'=>'img/eyesCat.jpg',
    'content'=> 'Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.',
    'author_id'=>4,
    'date'=>'2019-08-07',
    'likes'=> 9,
    ],
    ['title'=>'Horse',
    'image'=>'img/horse.jpg',
    'content'=>'Celery quandong swiss chard chicory earthnut pea potato. Salsify taro catsear garlic gram celery bitterleaf wattle seed collard greens nori. Grape wattle seed kombu beetroot horseradish carrot squash brussels sprout chard.',
    'author_id'=>4,
    'date'=>'2019-08-14',
    'likes'=> 11,
    ],
    ['title'=>'Sheep',
    'image'=>'img/sheep.jpg',
    'content'=> 'Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula pea tatsoi aubergine spring onion bush tomato kale radicchio turnip chicory salsify pea sprouts fava bean',
    'author_id'=>5,
    'date'=>'2019-08-13',
    'likes'=> 12,
    ],
    ['title'=>'Giraffe',
    'image'=>'img/giraffe.jpg',
    'content'=>'Nori grape silver beet broccoli kombu beet greens fava bean potato quandong celery. Bunya nuts black-eyed pea prairie turnip leek lentil turnip greens parsnip. Sea lettuce lettuce water chestnut eggplant winter purslane fennel azuki bean earthnut pea sierra leone bologi leek soko chicory celtuce parsley jícama salsify.',
    'author_id'=>5,
    'date'=>'2019-08-09',
    'likes'=> 114,
    ],
];


