<?php
// This is the file where you can keep your data arrays such as articles and
// authors.
declare(strict_types=1);

$authors = [
    ['id'=>1,
    'name'=>'Michaela Lundborg',
    ],
    ['id'=>2,
    'name'=>'Jacob Fridmar',
    ],
    ['id'=>3,
    'name'=>'Alexander Gustafsson Flink',
    ],
    ['id'=>4,
    'name'=>'Betsy Alva Soplin',
    ],
    ['id'=>5,
    'name'=>'Victor Ljungblad',
    ]
];


$posts = [
    ['title'=>'',
    'content'=> require __DIR__. '/post1.php',
    'author'=>$authors[0]['name'],
    'date'=>'2019-08-01',
    'likes'=> 10,
    ],
    ['title'=>'',
    'content'=>require __DIR__. '/post2.php',
    'author'=>'Micheala Lundborg',
    'date'=>'2019-08-21',
    'likes'=> 10,
    ],
    ['title'=>'',
    'content'=> require __DIR__. '/post1.php',
    'author'=>'Jacob Fridmar',
    'date'=>2019,
    'likes'=> 10,
    ],
    ['title'=>'',
    'content'=> require __DIR__. '/post2.php',
    'author'=>'Jacob Fridmar',
    'date'=>2019,
    'likes'=> 10,
    ],
    ['title'=>'',
    'content'=> require __DIR__. '/post1.php',
    'author'=>'Alexander Gustafsson Flink',
    'date'=>2019,
    'likes'=> 10,
    ],
    ['title'=>'',
    'content'=> require __DIR__. '/post2.php',
    'author'=>'Alexander Gustafsson Flink',
    'date'=>2019,
    'likes'=> 10,
    ],
    ['title'=>'',
    'content'=> require __DIR__. '/post1.php',
    'author'=>'Betsy Alva Soplin',
    'date'=>2019,
    'likes'=> 10,
    ],
    ['title'=>'',
    'content'=>require __DIR__. '/post2.php',
    'author'=>'Betsy Alva Soplin',
    'date'=>2019,
    'likes'=> 10,
    ],
    ['title'=>'',
    'content'=> require __DIR__. '/post1.php',
    'author'=>'Victor Ljungblad',
    'date'=>2019,
    'likes'=> 10,
    ],
    ['title'=>'',
    'content'=>require __DIR__. '/post2.php',
    'author'=>'Victor Ljungblad',
    'date'=>2019,
    'likes'=> 10,
    ],
];

die(var_dump($authors[0]['name']));