<?php
// This is the file where you can keep your data arrays such as articles and
// authors.
declare(strict_types=1);


$authors = [
    ['id'=>1,
    'name'=>'Michaela Lundborg',
    ],
    ['id'=>2,
    'name'=>'Jacob Fridmar',
    ],
    ['id'=>3,
    'name'=>'Alexander Gustafsson Flink',
    ],
    ['id'=>4,
    'name'=>'Betsy Alva Soplin',
    ],
    ['id'=>5,
    'name'=>'Victor Ljungblad',
    ]
];

$posts = [
    ['title'=>'Ett',
    'content'=> 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
     Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.' ,
    'author'=>$authors[0]['name'],
    'date'=>'2019-08-01',
    'likes'=> 10,
    ],
    ['title'=>'Två',
    'content'=> 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
    Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.',
    'author'=>$authors[0]['name'],
    'date'=>'2019-08-21',
    'likes'=> 10,
    ],
    ['title'=>'Tre',
    'content'=> 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
    Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.',
    'author'=>$authors[1]['name'],
    'date'=>'2019-08-20',
    'likes'=> 10,
    ],
    ['title'=>'Fyra',
    'content'=> 
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
    Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.',
    'author'=>$authors[1]['name'],
    'date'=>'2019-08-08',
    'likes'=> 10,
    ],
    ['title'=>'Fem',
    'content'=> 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
    Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.',
    'author'=>$authors[2]['name'],
    'date'=>'2019-08-03',
    'likes'=> 10,
    ],
    ['title'=>'Sex',
    'content'=> 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
    Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.',
    'author'=>$authors[2]['name'],
    'date'=>'2019-08-04',
    'likes'=> 10,
    ],
    ['title'=>'Sju',
    'content'=> 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
    Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.',
    'author'=>$authors[3]['name'],
    'date'=>'2019-08-07',
    'likes'=> 10,
    ],
    ['title'=>'Åtta',
    'content'=>'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
    Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.',
    'author'=>$authors[3]['name'],
    'date'=>'2019-08-14',
    'likes'=> 10,
    ],
    ['title'=>'Nio',
    'content'=> 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
    Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.',
    'author'=>$authors[4]['name'],
    'date'=>'2019-08-13',
    'likes'=> 12,
    ],
    ['title'=>'Tio',
    'content'=>'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt optio modi non natus?
    Accusamus repellat necessitatibus sit maiores dicta, ullam omnis doloribus alias obcaecati nam illum.',
    'author'=>$authors[4]['name'],
    'date'=>'2019-08-09',
    'likes'=> 114,
    ],
];


// $posts = [
//     ['title'=>'Ett',
//     'content'=> require __DIR__. '/post1.php',
//     'author'=>$authors[0]['name'],
//     'date'=>'2019-08-01',
//     'likes'=> 10,
//     ],
//     ['title'=>'Två',
//     'content'=> require __DIR__. '/post2.php',
//     'author'=>$authors[0]['name'],
//     'date'=>'2019-08-21',
//     'likes'=> 10,
//     ],
//     ['title'=>'Tre',
//     'content'=> require __DIR__. '/post1.php',
//     'author'=>$authors[1]['name'],
//     'date'=>'2019-08-20',
//     'likes'=> 10,
//     ],
//     ['title'=>'Fyra',
//     'content'=> require __DIR__. '/post2.php',
//     'author'=>$authors[1]['name'],
//     'date'=>'2019-08-08',
//     'likes'=> 10,
//     ],
//     ['title'=>'Fem',
//     'content'=> require __DIR__. '/post1.php',
//     'author'=>$authors[2]['name'],
//     'date'=>'2019-08-03',
//     'likes'=> 10,
//     ],
//     ['title'=>'Sex',
//     'content'=> require __DIR__. '/post2.php',
//     'author'=>$authors[2]['name'],
//     'date'=>'2019-08-04',
//     'likes'=> 10,
//     ],
//     ['title'=>'Sju',
//     'content'=> require __DIR__. '/post1.php',
//     'author'=>$authors[3]['name'],
//     'date'=>'2019-08-07',
//     'likes'=> 10,
//     ],
//     ['title'=>'Åtta',
//     'content'=>require __DIR__. '/post2.php',
//     'author'=>$authors[3]['name'],
//     'date'=>'2019-08-14',
//     'likes'=> 10,
//     ],
//     ['title'=>'Nio',
//     'content'=> require __DIR__. '/post1.php',
//     'author'=>$authors[4]['name'],
//     'date'=>'2019-08-13',
//     'likes'=> 12,
//     ],
//     ['title'=>'Tio',
//     'content'=>require __DIR__. '/post2.php',
//     'author'=>$authors[4]['name'],
//     'date'=>'2019-08-09',
//     'likes'=> 114,
//     ],
// ];
